### ISSUE TITLE
What are the advantages over a MSBuild configuration?

### ISSUE THREAD

**Issue by ite-klass** [Epsilekt/T4Executer#7]
How is this different from using the MSBuild `Microsoft.TextTemplating.targets` file and configuring it appropriately?

I presume only the easier (but also more limited) setup. Possibly also the include all but exclude some files approach.

I think it would be helpful to point out the differences, and point users to this alternative they may prefer (and should prefer unless they specifically want the features or do not care for the more technical, generic, and supported approach).

The project README and marketplace description would be a good place for this information.

**Comment by Epsilekt** [comment]
Hi ite-Klass

The reason I made this extension is because build events would not trigger the custom tool to run on T4 files in VS2017/2019 in my projects. The walkthrough in the Visual Studio Docs on the csproj approach dit not work for me either. 

If the supported approach works for you or anyone else, I can not argument why you should use T4Executer specifically, just the simplicity of specifying what templates to run pre or post build.

It was also my first shot at a VSIX project, and I decided to publish it. I'm planning on adding more configuration options in the near future though, and I will update the README and Marketplace for clarity, thanks for your feedback.
